### ISSUE TITLE
 Does not reset multi captcha

### ISSUE THREAD

**Issue by DmitrySkibitsky** [thinhbuzz/laravel-google-captcha#28]
js output
```js
<script type="text/javascript">
var buzzNoCaptchaWidgetIds={};
var buzzNoCaptchaOnLoadCallback=function( {
buzzNoCaptchaWidgetIds["captcha_create_comment"]=grecaptcha.render('captcha_create_comment',
{"sitekey":"6LdVmDEUAAAAABEyMLp_V2Yr52KOYC19aovieDuE", "id":"captcha_create_comment"}
);
buzzNoCaptchaWidgetIds["captcha_create_consultation"]=grecaptcha.render('captcha_create_consultation',
{"sitekey":"6LdVmDEUAAAAABEyMLp_V2Yr52KOYC19aovieDuE","id":"captcha_create_consultation"}
);
buzzNoCaptchaWidgetIds["captcha_create_appointment"]=grecaptcha.render('captcha_create_appointment',
{"sitekey":"6LdVmDEUAAAAABEyMLp_V2Yr52KOYC19aovieDuE","id":"captcha_create_appointment"}
);
};</script>
```

I execute in the console
```js
grecaptcha.reset(buzzNoCaptchaWidgetIds['captcha_create_consultation']);
```

As a result, the first captcha in the list of objects is reset (id captcha_create_comment)
Works as I understood on the same principle as before: the first counter is reset

**Comment by thinhbuzz** [comment]
you can post full source code?
I try with this code and package working perfectly: [multiple.blade.php](https://paste.laravel.io/74d52108-06c9-4b5f-97c5-f50c9e7a0b6a)

**Comment by DmitrySkibitsky** [comment]
Okay, I'm probably doing something wrong.

**Comment by DmitrySkibitsky** [comment]
https://github.com/DmitrySkibitsky/laravel-site-psychotherapy is source project

**Comment by thinhbuzz** [comment]
ok, i see 3 issue:

1. not need put `lang`, `sitekey`, `multiple` into `display` method
2. `displayJs` must be define before `displayMultiple`
3. can not use `multiple` or `setOptions` in master layout because section will be render before
for issue 3, i will be add default options to config file

And finally: options pass to `display` method does not apply global, if you want apply options for all captcha you can use `setOptions` method before render view

Thanks.

**Comment by DmitrySkibitsky** [comment]
@thinhbuzz , Thank you. Tomorrow I will understand.

**Comment by thinhbuzz** [comment]
you are wellcome
